### PR TITLE
changes for FGSL 1.5.0

### PR DESCRIPTION
**Pull request by reinh-bader**

### CODE REVIEW

**Comment by hhslepicka** [comment]
@reinh-bader do you have an estimate of when 1.5.0 will be available? Thank you! 👍

**Comment by ChristopherMayes** [comment]
@reinh-bader I am interested as well.

**Comment by reinh-bader** [comment]
Unfortunately I am currently rather inundated. Hope to have something ready by mid-June.

Cheers
Reinhold

**Comment by hhslepicka** [comment]
@reinh-bader do you have an update? Is there anything we can help with? Thank you!

Cheers

**Comment by reinh-bader** [comment]
Unfortunately, my official duties are currently overloading me, so pushing this out will be delayed, likely to end of July. 
If there is urgent need, I could try to get a beta archive done on shorter order, but without guarantees.

**Comment by hhslepicka** [comment]
@reinh-bader no need to rush a beta release. Thank you for the update.

**Comment by hhslepicka** [comment]
Thank you @reinh-bader! 🎉 🚀

**Pull request merged**
