### PR TITLE
preparatory work for 1.2.0 release

### PR DESCRIPTION
**Pull request by reinh-bader**

### CODE REVIEW

**Comment by tschoonj** [comment]
Don't worry about the Mac OS X builds starting later: these buildbots are in much higher demand as people use them to test iOS apps thereby creating a bit of a backlog...

**Comment by tschoonj** [comment]
Hi Reinhold, I added a commit that should fix the gsl version problem. You will need to pull this in before you commit anything else. Or if you already have, you will need to rebase against origin/fgsl_devel_1.2.0 after doing a fetch...

**Comment by reinh-bader** [comment]
Looks good. There still were some minor glitches, but these have been resolved. Linux builds now are OK, MAC still pending.

**Comment by reinh-bader** [comment]
I've done the merge and some more checking. If no further problems are reported I will make a new tag tomorrow and upload the archive to the download area.

**Comment by tschoonj** [comment]
Thanks for all the work Reinhold!

**Pull request merged**
